### ISSUE TITLE
Torrent and file spacing wrong?

### ISSUE THREAD

**Issue by SatoshiHP** [Bluewave2/legacy-4.3.8-qBittorrent#6]
The spacing per torrent, and per file on the Content tab, is too close together. It was not this close in 4.3.9. Or maybe it's the font.
I'm using it on 4.6.2
 
Is this a difference between 4.3.8 and 4.3.9?

I already switched back to 4.3.9. If this is indeed the difference between 4.3.8 and 4.3.9, I'll stay on 4.3.9. Let me know.

**Comment by SatoshiHP** [comment]
Also the icon to when you right click a file to 'open' is different in 4.3.9. But maybe that too is different than 4.3.8.

**Comment by Bluewave2** [comment]
> The spacing per torrent, and per file on the Content tab, is too close together. It was not this close in 4.3.9. Or maybe it's the font. I'm using it on 4.6.2
> 
> Is this a difference between 4.3.8 and 4.3.9?
> 
> I already switched back to 4.3.9. If this is indeed the difference between 4.3.8 and 4.3.9, I'll stay on 4.3.9. Let me know.

You're right it is, the content tab uses a universal value for spacing in newer versions, it was separate in older versions so that's why it's off, I had to choose between the transfer list, tab selectors etc. looking correct vs the content tab, It's not too bad but not what it was.




> Also the icon to when you right click a file to 'open' is different in 4.3.9. But maybe that too is different than 4.3.8.

4.3.8
![image](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/assets/83724034/ebd0f63a-aa2f-4efb-9ba6-be350ab969c9)

4.6 (theme)
![image](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/assets/83724034/7e566b69-4f69-46c2-9b0a-6144fbc51277)

there are minor differences that I thought were better than using the same generic icon for everything (i.e. force recheck icon) but maybe this is a 4.3.9 thing, i didn't use 4.3.9 so I'm not sure

**Comment by Bluewave2** [comment]
> Also the icon to when you right click a file to 'open' is different in 4.3.9. But maybe that too is different than 4.3.8.

oh no, I wasn't thinking, you meant the content tab, sorry, don't use it much myself

4.3.8
![image](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/assets/83724034/2906cfb6-ec3a-41ea-b500-96268bec4a09)

4.6 (theme)
![image](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/assets/83724034/7a5f3539-7110-4324-80ca-545d63b4987b)

You're right! I missed one, thank you, I don't have the time to fix it right now but I'll make sure I get it when I do.

**Comment by Bluewave2** [comment]
Issue fixed in https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/releases/tag/v1.19
